### ISSUE TITLE
Вынести списки пользователей в отдельные таблицы

### ISSUE THREAD

**Issue by I1yi4** [be-Cycled/beCycled-backend#19]
У Тренировки, гонки и сообществ есть список участников. Сейчас это просто поле типа массив. Прикол в том что postgresql не умеет во внешние ссылки для массивов. Если пользователь удаляется его нужно удалять и из всех сущностей. А то получится что в сообществе только мертвые души

**Comment by binakot** [comment]
Надо сделать это ASAP! Плюс навернуть правильные референсы на каскадное удаление и ограничение челостности
