### ISSUE TITLE
Поменять тип поля venue в сущности workout и competition

### ISSUE THREAD

**Issue by avkoltovich** [be-Cycled/beCycled-backend#27]
В данный момент это поле имеет тип - String.
Мне же надо, чтобы это была мапа.

**Comment by avkoltovich** [comment]
В мапе должно быть два свойства - lng и lat. Это координаты, числа с плавающей точкой.

**Comment by binakot** [comment]
В этом случае лучше вынести место сбора во внешнюю таблицу. Нельзя пихать в один столбец 2 значения. Тут либо добавлять 2 столбца venue_latitude, venue_longitude. Либо делать отдельную таблицу location с полями name (наименование места), и пара latitude и longitude. А уже в таблице workout и competition указывать venue_location_id как внешнюю ссылку на место

**Comment by avkoltovich** [comment]
Наименование места точно лишнее. Эту штуку переиспользовать не будут. Эти точки имеют ценность только в рамках ивента. Может мне не парить мозг, да в строку JSON просто загонять эти данные? Как я это делаю с полем routeInfo?

**Comment by binakot** [comment]
Ну да, давайте сделаем поле venueInfo

**Comment by binakot** [comment]
routeInfo -> routeGeoData : TEXT
venue -> venueGeoData : TEXT
