### ISSUE TITLE
Добавить поле link (ссылка) сущности baseEvent

### ISSUE THREAD

**Issue by avkoltovich** [be-Cycled/beCycled-backend#48]
Возникла потребность в добавлении такого поля.
При создании роллерской покатушки, а также при создании велосоревнования пришлось ссылку добавлять в описание.

Ссылка вполне себе может часто быть. Например, на официальную страницу мероприятия.

**Comment by mephistorine** [comment]
Поле лучше назвать так же как в Сообществах — `url`
